export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  customers: "/customers",
  employees: "/employees",
  salesOpportunities: "/sales-opportunities",
  inputRecords: "/input-records",
  bookingDeployment: "/booking-deployment",
  revenue: "/revenue",
  acceptanceLiquidation: "/acceptance-liquidation",
  paymentCollection: "/payment-collection",
  invoices: "/invoices",
  locationInspection: "/location-inspection",
  locationPerformance: "/location-performance",
  periodicReports: "/periodic-reports",
  contracts: "/contracts",
  documentArchive: "/document-archive",
  settings: "/settings",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  twoStepVerification: "/two-step-verification",
  forgotPasswordVerify: "/forgot-password-verify",
  maintenance: "/maintenance",
  comingSoon: "/coming-soon",
  notAuthorized: "/not-authorized",
} as const

export type Route = (typeof ROUTES)[keyof typeof ROUTES]
