import type { PaginationParams } from "@/types"
import {
  CUSTOMER_CLASSIFICATIONS,
  CUSTOMER_COUNTRIES,
  CUSTOMER_INDUSTRIES,
  CUSTOMER_STATUSES,
  VIETNAM_PROVINCES,
} from "./constants"

export type CustomerStatus = (typeof CUSTOMER_STATUSES)[number]
export type CustomerClassification = (typeof CUSTOMER_CLASSIFICATIONS)[number]
export type CustomerIndustry = (typeof CUSTOMER_INDUSTRIES)[number]
export type CustomerCountry = (typeof CUSTOMER_COUNTRIES)[number]
export type VietnamProvince = (typeof VIETNAM_PROVINCES)[number]

export interface Customer {
  id: string
  /** Auto-generated by the backend (mock: mock-data.ts). Never user-supplied. */
  code: string
  /**
   * Count from the (not-yet-built) Sales Opportunities feature. Mocked here
   * as a plain counter — defaults to 0 for a new customer — until that
   * feature exists and can own this number for real.
   */
  opportunityCount: number

  name: string
  email: string
  phone: string
  company: string
  classification: CustomerClassification
  industry: CustomerIndustry
  status: CustomerStatus

  shortName?: string
  taxCode?: string
  website?: string
  address?: string
  country?: CustomerCountry
  /** Only meaningful when country === "vietnam". */
  province?: VietnamProvince

  /** Employee.id — "NVKD phụ trách". */
  salesRepId?: string
  /** Employee.id — "QLHĐ phụ trách". */
  contractManagerId?: string

  representativeName?: string
  representativePosition?: string
  representativeMobile?: string
  representativeEmail?: string

  contactName?: string
  contactPosition?: string
  contactMobile?: string
  contactEmail?: string

  mediaContactName?: string
  mediaContactPosition?: string
  mediaContactMobile?: string
  mediaContactEmail?: string

  /** Mocked upload: only the picked file's name is recorded, no bytes are stored. */
  avatarFileName?: string
  /** Set by a real backend after it stores the file. Always undefined in mock mode. */
  avatarUrl?: string

  notes?: string
  review?: string

  createdAt: string
}

export interface CreateCustomerInput {
  name: string
  email: string
  phone: string
  company: string
  classification: CustomerClassification
  industry: CustomerIndustry
  status: CustomerStatus
  // Required per business rule (see schemas.ts's createCustomerSchema) — a
  // *creation* payload must carry all four; a persisted Customer record may
  // still lack them if it predates the rule (hence optional on Customer).
  shortName: string
  taxCode: string
  salesRepId: string
  contractManagerId: string
  website?: string
  address?: string
  country?: CustomerCountry
  province?: VietnamProvince
  representativeName?: string
  representativePosition?: string
  representativeMobile?: string
  representativeEmail?: string
  contactName?: string
  contactPosition?: string
  contactMobile?: string
  contactEmail?: string
  mediaContactName?: string
  mediaContactPosition?: string
  mediaContactMobile?: string
  mediaContactEmail?: string
  avatarFileName?: string
  notes?: string
  review?: string
}

export type UpdateCustomerInput = Partial<CreateCustomerInput>

export interface CustomerFilters {
  search?: string
  classification?: CustomerClassification
  industry?: CustomerIndustry
  status?: CustomerStatus
}

export interface GetCustomersParams extends PaginationParams, CustomerFilters {}

// Canonical status → Badge variant mapping (mirrors employees/types.ts's own
// STATUS_VARIANT) — kept independent of employees' map since the two status
// enums no longer share any values.
export const STATUS_VARIANT: Record<CustomerStatus, "success" | "warning" | "info"> = {
  collaborating: "success",
  paused: "warning",
  potential: "info",
}

// Minimal projection for customer pickers in other features (e.g. the sales
// opportunities filter bar/table). Deliberately excludes email/phone/taxCode/
// address/contacts/notes — a picker in an unrelated feature has no business
// receiving the full Customer record just to render a dropdown label.
//
// `code` is included on purpose: customer *names* are person names that
// repeat and look alike, while `code` ("2VT-C00001") is the business-unique
// identifier users actually recognize — rendered as "Tên khách hàng · Mã KH",
// the same way the employee picker renders "tên · phòng ban".
export interface CustomerOption {
  id: string
  name: string
  code: string
}
